name: Fetch Latest Psyc
description: Retrieve a 'psyc' executable from the latest release or pre-release

runs:
  using: "composite"
  steps:
    # Windows
    - name: Install Psyc (Windows)
      if: runner.os == 'Windows'
      shell: cmd
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        mkdir -p tools
        gh release download ^
            --repo "%GITHUB_REPOSITORY%" ^
            --pattern "psyc.exe" ^
            --dir tools
        echo "%GITHUB_WORKSPACE%/tools" >> %GITHUB_PATH%
        
    # Linux
    - name: Install Psyc (Linux)
      if: runner.os == 'Linux'
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        mkdir -p tools
        gh release download \
            --repo "$GITHUB_REPOSITORY" \
            --pattern "psyc.elf" \
            --dir tools
        echo "$GITHUB_WORKSPACE/tools" >> $GITHUB_PATH
        chmod +x $GITHUB_WORKSPACE/tools/psyc.elf

