name: Fetch Latest Psyc
description: Retrieve a 'psyc' executable from the latest release or pre-release

runs:
  using: "composite"
  steps:
    # Windows
    - name: Install Psyc (Windows)
      if: runner.os == 'Windows'
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        mkdir -p tools
        gh release download llvm_19_1_5 \
            --repo "c3lang/win-llvm" \
            --pattern "llvm-19.1.5-windows-amd64-msvc17-libcmt.7z"
        7z x llvm-19.1.5-windows-amd64-msvc17-libcmt.7z -Ollvmc
        echo "llvmc/bin" >> $GITHUB_PATH
        echo "llvmc/lib" >> $GITHUB_PATH

        gh release download \
            --repo "$GITHUB_REPOSITORY" \
            --pattern "psyc.exe" \
            --dir tools
        echo "$GITHUB_WORKSPACE/tools" >> $GITHUB_PATH
		echo "curdir = $cd $pwd %cd%"
        
    # Linux
    - name: Install Psyc (Linux)
      if: runner.os == 'Linux'
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        mkdir -p tools
        sudo apt install llvm-19-dev
        gh release download \
            --repo "$GITHUB_REPOSITORY" \
            --pattern "psyc.elf" \
            --dir tools
        echo "$GITHUB_WORKSPACE/tools" >> $GITHUB_PATH
        chmod +x $GITHUB_WORKSPACE/tools/psyc.elf

