name: "run-samples"
description: "Download a previously-generated psyc and try to compile some stuff with it."

runs:
  using: "composite"
  steps:
    - name: minimal.psy
      shell: bash
      run: ./psyc -v ./samples/minimal.psy --dump-ast --dump-ir

    - name: scratchpad.psy
      shell: bash
      run: ./psyc -v ./samples/scratchpad.psy --dump-ast --dump-ir