name: "run-tests"
description: "Download a previously-generated psyc and try to compile some stuff with it."

inputs:
  build_config:
    required: true
    type: string
  compiler:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4

    - name: Retrieve psyc
      uses: actions/download-artifact@v4
      with:
        name: psyc_${{ inputs.compiler }}_${{ inputs.build_config }}

    - name: scratchpad.psy
      shell: bash
      run: psyc -v ./samples/scratchpad.psy --dump-ast --dump-ir