name: "clang"
on:
  workflow_call:
    inputs:
      build_config:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: 'Install Vulkan SDK'
        uses: humbletim/install-vulkan-sdk@v1.1.1
        if: ${{inputs.render_api == 'vulkan'}}

      - name: 'Configure psyc clang_${{inputs.build_config}}'
        run: cmake --preset ${{inputs.build_config}} -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang
        working-directory: cpp

      - name: 'Build psyc clang_${{inputs.build_config}}'
        run: cmake --build ./build/${{inputs.build_config}} --target psyc
        working-directory: cpp

