name: "clang"
on:
  workflow_call:
    inputs:
      build_config:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: 'Automatic LLVM Install'
        run: sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)" 

      - name: 'Configure psyc clang_${{inputs.build_config}}'
        run: cmake --preset ci_${{inputs.build_config}} -DCMAKE_CXX_COMPILER=clang++-18 -DCMAKE_C_COMPILER=clang-18
        working-directory: cpp

      - name: 'Build psyc clang_${{inputs.build_config}}'
        run: cmake --build ./build/ci_${{inputs.build_config}} --target psyc
        working-directory: cpp

      - name: 'Compile a simple test program'
        run: ./cpp/build/ci_${{inputs.build_config}}/psyc -v ./samples/scratchpad.psy --dump-ast --dump-ir

