name: "gcc"
on:
  workflow_call:
    inputs:
      build_config:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: 'Automatic LLVM Install'
        run: sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)" 

      - name: 'Install newer GCC'
        run: sudo apt install gcc-12 

      - name: 'Configure psyc gcc_${{inputs.build_config}}'
        run: cmake --preset ci_${{inputs.build_config}} -DCMAKE_CXX_COMPILER=g++-12 -DCMAKE_C_COMPILER=gcc-12
        working-directory: cpp

      - name: 'Build psyc gcc_${{inputs.build_config}}'
        run: cmake --build ./build/ci_${{inputs.build_config}} --target psyc
        working-directory: cpp

