name: "clang"
on:
  workflow_call:
    inputs:
      build_config:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: 'Automatic LLVM Install'
        run: sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)" 

      - name: 'Configure psyc clang_${{inputs.build_config}}'
        run: cmake --preset ci_${{inputs.build_config}} -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang
        working-directory: cpp

      - name: 'Build psyc clang_${{inputs.build_config}}'
        run: cmake --build ./build/ci_${{inputs.build_config}} --target psyc
        working-directory: cpp

