name: "code builds (debug)"

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  clang_linux:
    uses: Harrand/Topaz/.github/workflows/build_clang.yml@master
    with:
      build_config: debug