name: "Hello World"
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Fetch compiler
        uses: actions/download-artifact@v4
        with:
          name: psyc-win32-latest
      - name: Write basic hello world program
        shell: pwsh
        run:  |
          Set-Content helloworld.psy 'main ::= func(-> s32){return 0;}; == default == {}'
      - name: Compile program
        shell: cmd
        run:  |
          psyc helloworld.psy
