name: "Hello World"
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Fetch compiler binary
        uses: ./.github/actions/fetch-compiler-win32
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Write basic hello world program
        shell: pwsh
        run:  |
          Set-Content helloworld.psy 'main ::= func(-> s32){return 0;}; == default == {}'
      - name: Compile program
        shell: cmd
        run:  |
          psyc helloworld.psy
