name: "Hello World"
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Fetch compiler binary
        uses: ./.github/actions/fetch-latest-psyc
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Write basic hello world program
        shell: pwsh
        run:  |
        Set-Content helloworld.psy 'main ::= func(argc : s32, argv : u8??, penv : u8?? -> s32){putzstr("Hello World!"); return 0;}; == default == {add_source_directory("src/stdlib"); add_link_library("Kernel32.lib"); add_link_library("Shell32.lib");}'
      - name: Compile program
        shell: cmd
        run:  |
          psyc helloworld.psy
