name: "Hello World"
on:
  push:
    branches: [ master ]
jobs:
  fetch-compiler:
    uses: ./.github/workflows/fetch-compiler-win32.yml
  build:
    runs-on: windows-latest
    needs: fetch-compiler
    steps:
      - name: Write basic hello world program
        shell: pwsh
        run:  |
          Set-Content helloworld.psy 'main ::= func(-> s32){return 0;}; == default == {}'
      - name: Compile program
        shell: cmd
        run:  |
          psyc helloworld.psy
